### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by cristian-sima** [balloob/react-sidebar#57] opened 2016-07-12 16:09 UTC
I tested the sidebar using https://github.com/reactjs/react-a11y
and I got these 4 problems

![image](https://cloud.githubusercontent.com/assets/12199042/16774317/25e657b2-4864-11e6-960a-13843327bdce.png)
 and
![image](https://cloud.githubusercontent.com/assets/12199042/16774321/2c463500-4864-11e6-8373-c293594a2396.png)

**Comment by balloob** [comment] 2016-07-12 17:53
Duplicate of #56

**Closed by balloob** 2016-07-12 17:53 UTC
